export interface KonyaSchoolItem {
  name: string;
  type: string;
  district: string;
}

export const KONYA_SCHOOL_CATALOG: KonyaSchoolItem[] = [
  {"name": "KONYA - KARATAY - Abdülhamid Han Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Akabe İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Akabe İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Akçesme İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Akif Paşa İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Alaeddin Keykubad İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Aliye-Hüseyin Tekbaş İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Aynur Kasabalı İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Ayşe Hüseyin Özkan İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Ayşe Hüseyin Özkan İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Ayşe-Hüseyin Özkan Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Birol Polat İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Bozkırlılar Vakfı İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Bozkırlılar Vakfı Kız Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Büyük Sinan Mehmet Fatma Dalan İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Çatalhüyük Anadolu Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Çatalhüyük Melikşah İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Çatalhüyük Münise Lütfi Onat İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Celaleddin Karatay Tarım Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Cemil Keleşoğlu Anadolu Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Cengiz Topel İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Çumralıoğlu Vakfı Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Doktor Sedat Yüksel İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Dr.Ali Rıza Bahadır Kız Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Fetihkent İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Gevher Nesibe Hatun İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - GÖÇÜ İLKOKULU", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Göçü Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Hacı Sadık İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Hacı Yusuf Mescit Ahmet Haşhaş İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Hacıveyiszade Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Hacıveyiszade Mahallesi Ahmet Haşhaş İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Halil Bahçeci İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Hamzaoğlu İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Hasan Ali Yücel İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Hayıroğlu İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Hayıroğlu İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Hediye-Mehmet Ali Uzman İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Hüseyin Sevim Köroğlu İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - İbrahim Sulhiye Kamanlı İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - İlhan-Nuran Keskin İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - İSA CAN BEZİRCİ İMAM HATİP ORTAOKULU", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - İsa Can Bezirci Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - İsmet Paşa İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - İstiklal İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - İstiklal Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - İzzet Bezirci İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karaaslan Atatürk İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karaaslan Atatürk Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karaaslan Cumhuriyet İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay 15 Temmuz Şehitleri Anadolu Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay Ali Ulvi Kurucu Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay Aykent Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay Belediyesi 23 Nisan İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay Belediyesi İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay Belediyesi Osman Benliler İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay Borsa İstanbul Gazi Mustafa Kemal Turizm Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay Borsa İstanbul Zübeyde Hanım Kız Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay Fen Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay Hamza Yerlikaya Spor Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay Hürriyet Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay İlhan-Nuran Keskin Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay Kocatepe İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay Nermin-Agah-Erdinç Topak Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay Sadreddin Konevi Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay Ticaret Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karatay TOKİ Anadolu Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Karkent İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Kılıçarslan Borsa İstanbul Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Konya Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Konya Türk Telekom Sosyal Bilimler Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Koyunoğlu İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Kurtuluş Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Kuvayi Milliye İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Mahide Koşukçu İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Mehmet-Hanife Yapıcı Anadolu Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Mehmetçik İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Mehmetçik İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Mevlana Kız Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Müslüme Ali Yaman İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Mustafa Aydın İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Namık Kemal Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Nermin Agah Erdinç Topak İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Nizamülmülk Anadolu Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Orhan Gazi İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Ovakavağı İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Ovakavağı İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Prof. Dr. Fuat Sezgin Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Prof.Dr.Ömer Dinçer Kız Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Saraçoğlu Ahmet Haşhaş İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Saraçoğlu İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Saraçoğlu Toki Mustafa Çetin İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Şehit Albay İbrahim Karaoğlanoğlu İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Şehit Azam Güdendede Anadolu Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Şehit Erol Olçok İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Şehit Sadık Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - ŞEHİT ÜSTEĞMEN MEHMET DÜZENLİ İMAM HATİP ORTAOKULU", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Şekibe Aksoy İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Sezai Karakoç İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Süleyman Şah Anadolu Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Sultan Alparslan İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Tatlıcak Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Türk Anadolu Vakfı Hafız Kız Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Ulubatlı Hasan İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Uluırmak Hürriyet İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - VALİ KEMAL KATITAŞ İLKOKULU", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Yağlıbayat Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Yarma İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Yarma Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Yaşar Doğu Ortaokulu", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Yavuz Selim İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Yenikent İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - YENİKENT ORTAOKULU", "type": "ORTAOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Yusuf Gül İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - KARATAY - Zeliha Seymen İlkokulu", "type": "İLKOKUL", "district": "KARATAY"},
  {"name": "KONYA - MERAM - 15 Temmuz Milli Birlik İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - 15 Temmuz Şehitleri İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - 24 Kasım İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Abdussamet Fazilet Kuzucu İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Ahmet Azmi-Makbule Elberk İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Ahmet Naci Gücüyener İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Ahmet Tevfik İleri İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Alakova İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Alakova Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Ali İhsan Dayıoğlugil İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Ali Taşoluk İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Atatürk İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Aybahçe Mah. Ahmet Haşhaş İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Aybahçe Toki Şehit Süleyman Ballan İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Ayşe Sönmez İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Boruktolu İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Boruktolu Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Çarıklar İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Çarıklar Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Çayırbağı İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Celalettin Hakan Katırcı İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Çelebi Hüsameddin Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Cemal Bardakçı İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Çomaklı İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Çomaklı Talip Kahraman Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Cumhuriyet İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Dere İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Dr. Teoman Bilge İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Emlak Konut Temaşehir Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Faik Altıoklar İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Faik Altıoklar Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Fatih Sultan Mehmet İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Fevzi Çakmak Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Gödene Orhan Gazi İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Gödene Toki İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Gödene Toki Şehit Abdullah Paltacı Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Gökyurt İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Gökyurt Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Güneydere İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Güneydere Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Hadimi Anadolu Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Hanefi Aytekin İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Hatıp İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Hatıp Öğretmen Mahide Bahadırtürk Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Hatunsaray İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Hatunsaray İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - İbrahim Ethem Kız Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - İbrahim Hakkı Konyalı İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - İhsan Özkaşıkcı İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - İnlice İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - İnlice Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - İsmail-Adile Avcan İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - KARADİĞİN DERESİ İLKOKULU", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Karadiğin Yeniaylar İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Karadiğin Yeniaylar Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Karahüyük Mah. Ahmet Haşhaş İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Kaşınhanı Cumhuriyet İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Kaşınhanı Cumhuriyet Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Kaşınhanı İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Kemal Hatipoğlu İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Konya Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Konya Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Kozağaç Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Mehmet Akif Ersoy Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Mehmet Beğen Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Mehmet Hasan Sert İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Mehmet Karaciğanlar Mevlana İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Mehmet Şükriye Sert İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram 75. Yıl Kız Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Ali Yaman İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Ali Yaman Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Alparslan Anadolu Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Anadolu Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Atatürk Kız Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Aybahçe Toki Şehit Süleyman Ballan İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Beybes Şehit Öğretmen Hüseyin Yavuz İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Çayırbağı Tahsin-Özlem Bengisu Emiroğlu Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Çayırbağı Tahsin-Özlem-Bengisu Emiroğlu İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Dere Cumhuriyet İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Dere Zafer İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Fen Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Gödene İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Gödene Toki Şehit Yunus Berber İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Harmancık Toki Ziya Nur Aksun Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Hasanköy İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Kaşınhanı Atatürk İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Lalebahçe Mehmet Fevzi ve Atiye Atçeken İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Mehmet Akif İnan Anadolu Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Mehmet ve İbrahim Çelik İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - MERAM MEHMET-KADİR ÖZGÜZAR İLKOKULU", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Mehmet-Kadir Özgüzar Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Mehmet-Münevver Kurban Anadolu Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Mustafa Bağrıaçık İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Mustafa Bağrıaçık Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Niyaz Usta İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Özcan-Saliha Çalıkuşu İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Şehit Pilot Ayfer Gök Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Şeyh Şamil İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Şifa Hatun Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Turan Bilge İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Meram Turan Bilge Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Muhittin Güzelkılınç İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Mümtaz Koru Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Mustafa İlboğa Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Naciye Mumcuoğlu Anadolu Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Necip Fazıl Kısakürek İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Nuri Pakdil Anadolu Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Osman Gazi Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Rukiye Mehmet Akış Fen ve Teknoloji Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Sare Özkaşıkcı Yatılı Bölge Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Şehit Abdullah Ümit Sercan İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Şehit Ahmet Senih Durum İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Şehit Fethi Sekin Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Şehit Mehmet- Lütfi Gülşen Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Şehit Ömer Halisdemir İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Selçuk İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Şerife Mevlüt Harmankaya Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Şükrü Doruk Kız Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Tahir Büyükkörükçü Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Telafer İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Ticaret Borsası Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Uhut Mahallesi Ahmet Haşhaş İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Üresinler İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Vakıfbank İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Vali Necati Çetinkaya Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Yaka Çumralıoğlu İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Yavuz Sultan Selim İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Yavuz Sultan Selim Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Yaylapınar Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Yenibahçe İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Yenibahçe Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Yeşildere Firuzan Işık İzmirligil İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Yeşildere Firuzan Işık İzmirligil Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Yıldız Kız Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - MERAM - Yunus Emre İlkokulu", "type": "İLKOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Zafer Ortaokulu", "type": "ORTAOKUL", "district": "MERAM"},
  {"name": "KONYA - MERAM - Zeki Özdemir Anadolu Lisesi", "type": "LİSE", "district": "MERAM"},
  {"name": "KONYA - SELÇUKLU - 100. Yıl Mahallesi Ahmet Haşhaş Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - 100.Yıl Ahmet Haşhaş İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - 15 Temmuz Şehitleri İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Abdülezel Paşa İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Abidin Saniye Erçal İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Adil Karaağaç Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Adnan Akgül Özel Eğitim Meslek Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Adnan Hadiye Sürmegöz Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Ahmet Acar İlkokul", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Ahmet Hazım Uluşahin İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Ahmet Karacigan Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Ahmet Perihan Demirok İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - AKINCILAR MAHALLESİ AHMET HAŞHAŞ İLKOKUL", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Akşemseddin İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Alaeddin İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Aliya İzzetbegoviç Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - ASELSAN KONYA Meslekî ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Atatürk Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Atatürk Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Ayşe - Kemal İnanç Kız Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Ayşe Tümer İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Ayşe-Kemal İnanç İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Barbaros İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Beyhekim İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Borsa İstanbul Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Bosna Hersek Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Buhari Kız Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Büyükbayram Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Cahit Zarifoğlu İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Cemil Meriç Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Cemile Erkunt İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Cumhuriyet Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Cumhuriyet Mahallesi Ahmet Haşhaş Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Dikilitaş Sahip Ata İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Dolapoğlu Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Dr. Mustafa Öten İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Dumlupınar Mahallesi Ahmet Haşhaş İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Dursun Fakih Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Erbil Koru Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Erdem Bayazıt Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Erenköy Zeki Altındağ İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Erenköy Zeki Altındağ Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Ertuğrul Gazi Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Eşrefoğlu İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Fatih Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Fatih Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Gazi Kız Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Hakim Ömer Onsun İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Hamidiye İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Hoca Ahmet Yesevi Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Hocacihan Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Hocacihan Hüseyin Yıldız İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Hocacihan Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - İbrahim Yapıcı İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - İhsaniye İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - İsmail Hakkı Tonguç İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - İsmail Kaya Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Kanuni Sultan Süleyman İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Kaşgarlı Mahmut Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Kazım Özenç Seçen Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Kemal Akpınar İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Kemal Rızvanoğlu İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Konevi Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Konya Çimento Güzel Sanatlar Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - KOSOVA ORTAOKULU", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - M. Halil İbrahim Hekimoğlu Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mahmud Celaleddin Ökten Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mahmut Sami Ramazanoğlu Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mahmut Sami Ramazanoğlu Kız Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mareşal Mustafa Kemal Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mehmet Akdoğan Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mehmet Akif Ersoy Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mehmet Ali Atiker İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mehmet Halil İbrahim Hekimoğlu Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mehmet Nuri Küçükköylü İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mehmet Tuza Pakpen Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mehmet Zahid Kotku Kız Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mimar Sinan İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Muhammed Hamdi Yazır İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mümine Hatun Kız Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mustafa Bülbül Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mustafa Büyükkaplan Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mustafa Fevzi Serin İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mustafa Hotamışlı Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mustafa Karaciğan İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Mustafa Necati İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Necip Fazıl Kısakürek Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Nene Hatun İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Nesrin ve Ayşegül Kardeşler İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Nurcan Akpınar İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Öğretmen Fethiye Onsun İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Oğuz Kağan İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Ömer Cemile Güler İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Osman Nuri Hekimoğlu Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Osmangazi İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Ova Un İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Özel İdare 100. Yıl İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Öztekinler Kız Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Piri Reis İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Prof. Dr. Mahmut Esad Coşan İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Rebii Karatekın Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - taokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Saraybosna Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - ip Olçok İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Şehit İbrahim Betin İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Şehit Mustafa Çuhadar Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Şehit Osman Demir İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Şehit Teğmen Bayram Olgun İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Şehit Ufuk Baysan Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Selahaddin Eyyubi Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Selçuklu Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Selçuklu Belediyesi İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Selçuklu Belediyesi İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Selçuklu Belediyesi Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Selçuklu Belediyesi Şehit Erkan Kurşun İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Selçuklu Belediyesi Sille İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Selçuklu Fen Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Selçuklu Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Şems-i Tebrizi Kız Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Şerife Akkanat İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Şerife Akkanat Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Seyit Ulugülyağcı İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Sıraç Aydıntaşbaş İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Şükriye Onsun İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Süleyman Çelebi Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Sultan Mesut İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Talha Bayrakçı Kız Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - TOKİ İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Türk Anadolu Vakfı İmam Hatip Ortaokulu", "type": "ORTAOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Türk Telekom Mesleki ve Teknik Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Uluslararası Mevlana Anadolu İmam Hatip Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Vali İhsan Dede Anadolu Lisesi", "type": "LİSE", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Yazır Şehit Osman Küçükdillan İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Zeki Altındağ İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
  {"name": "KONYA - SELÇUKLU - Zeliha ve Lütfi Kulluk İlkokulu", "type": "İLKOKUL", "district": "SELÇUKLU"},
];
